### ISSUE TITLE
Process timeout setting

### ISSUE THREAD

**Issue by hernit** [handcraftedbits/go-bamboo-plugin#11]
We are encountering some issues with this plugin.
`2016-06-16 13:16:21,328 INFO [15-BAM::Local Agent 1::Agent:pool-30-thread-1] [TaskResultBuilder] CGA-LIS2-BP-16: Failing task since return 
code of [/usr/local/go/bin/go test -v ./...] was -1 while expected 0
2016-06-16 13:16:21,328 INFO [15-BAM::Local Agent 1::Agent:pool-30-thread-1] [TaskResultBuilder] Process exception: 
com.atlassian.utils.process.ProcessTimeoutException: process timed out
        at com.atlassian.utils.process.ExternalProcessImpl.wrapUpProcess(ExternalProcessImpl.java:663)
        at com.atlassian.utils.process.ExternalProcessImpl.finish(ExternalProcessImpl.java:161)
        at com.atlassian.utils.process.ExternalProcessImpl.execute(ExternalProcessImpl.java:114)
        at com.handcraftedbits.bamboo.plugin.go.task.common.ProcessHelper.executeProcess(ProcessHelper.java:95)
        at com.handcraftedbits.bamboo.plugin.go.task.test.GoTestTaskType.execute(GoTestTaskType.java:90)
        at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$120(TaskExecutorImpl.java:269)
        at com.atlassian.bamboo.task.TaskExecutorImpl$$Lambda$209/825808799.call(Unknown Source)
        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:202)
        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:269)
        at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:108)
        at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:74)
        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:214)
        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:139)
        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:130)
        at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:215)
        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:129)
        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:136)
        at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
        at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
        at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
        at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
        at java.lang.Thread.run(Thread.java:745)`

We believe this is due to the plugin ProcessHelper using the default com.atlassian.utils.process.ExternalProcess timeout setting.

Can this be configurable? Sort of like this?
https://github.com/smitcham/bamboo-git-plugin/blob/master/src/main/java/com/atlassian/bamboo/plugins/git/GitCommandProcessor.java#L350

**Comment by handcraftedbits** [comment]
Sure thing, I'll take a look at this as soon as I can.

**Comment by blind-oracle** [comment]
Yes it times out exactly after one minute. It's bad because our tests run longer :(
